### ISSUE TITLE
Static content

### ISSUE THREAD

**Issue by prettykool** [bit-bandit/parasite#10]
Discuss how static content should be handled here.

**Comment by prettykool** [comment]
Static content has been added as of commit [12b26a986b93b7dfdd38702dfdc53ccf27eb6684](https://github.com/bit-bandit/parasite/commit/12b26a986b93b7dfdd38702dfdc53ccf27eb6684). The tree of the content is like so:
```
static
  |
  '--- m
       |--- defaults              // Default avatar/icon presets.
       '--- u
            '--- {id}             // Where id = User id
                  |--- avatar.png // Avatar of the user.
                  '--- banner.png // Banner of the user.
```
This is a pretty rigid structure, and I think it works well enough for what Parasite is suited for. 
```

**Comment by zegfarce** [comment]
Discussed with pk: `defaults` is being renamed to `defs`, for brevity.
