### ISSUE TITLE
Torrents

### ISSUE THREAD

**Issue by prettykool** [bit-bandit/parasite#2]
Discuss how Torrents should be handled here.

**Comment by prettykool** [comment]
Sample torrent JSON

```
{
   "@context":"https://www.w3.org/ns/activitystreams",
   "id":"https://torrents.sickos.social/t/500df719166b",
   "type":"Note",
   "published":"2022-02-13T22:33:24.315Z",
   "attributedTo":"https://torrents.sickos.social/u/larvae",
   "name": "Sintel (Torrent)",
   "content":"<p>Have a torrent you won't get sued over! Kudos to the Blender foundation for making this one, and for free!</p>",
   "tag": [
      {
        "id": "https://torrents.sickos.social/tags/fantasy", // This is in the spec, which is why I was trying to push it earlier...
        "name": "Fantasy"
      }
    ],
    "attachment": {
         "type": "Link",
         "href": "magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent"
         },
   "to":["https://www.w3.org/ns/activitystreams#Public"],
   "replies": "https://torrents.sickos.social/t/500df719166b/c"
}
```
The attachment field must include one magnet link. All torrents, for the time being, are totally public - Not like private torrents need a reason to exist. 

An ID for a torrent will always be a completely random 12-digit alphanumeric string.

As for what should be sent to the server, here's an example down below. ? indicates an array that can be left blank.

```json
{
  title: "Title used here",
  body?: "Description of **torrent**",
  magnet: "MagnetLink", 
  tags?: ["Array", "Of", "Tags"]
}
```

The body should be formatted in Markdown. This is just because it's easier to control user input with it. I'm not sure how tags should be processed/handled, yet. 

All user authentication should be taken care of in the Authorization field in the HTTP request header.

If a field is blank, the following response will be returned, alongside a 404 error:

```
"err": true,
"msg": "Field ${FIELD} blank"
``` 

`${FIELD}` being the field left blank, in question.

If there's something you think I missed, please tell me.

**Comment by zegfarce** [comment]
Similar to lists, I think it'd be more productive to simplify the `"attachment"` field to just storing the link itself.

**Comment by prettykool** [comment]
> Similar to lists, I think it'd be more productive to simplify the `"attachment"` field to just storing the link itself.

That might seem productive, but it might lead to issues in the future.

Just looking at ActivityStreams standard for links, we can see that all examples given explicitly use the `{ "type": "Link" }` syntax. Just for some examples: 
https://www.w3.org/TR/activitystreams-vocabulary/#dfn-link
https://www.w3.org/TR/activitystreams-vocabulary/#dfn-href
https://www.w3.org/TR/activitystreams-vocabulary/#dfn-attachment

I'm not sure what problems it might cause if we don't include it, but it's better to be safe than sorry, I suppose.

This may end up having to apply to lists, too.
