### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by prettykool** [bit-bandit/parasite#5]
Discuss how searching should be handled here.

**Comment by prettykool** [comment]
Broadly, the format should be `/s?q=foo`, as it's a fairly common, and easy to digest model.

The question is, how should we use it?

Ideally, we should be able to query as much data from the engine as possible, including:

- Title of object (which can be either a list, a torrent, or a user)
- Description of object (Where applicable)
- Rating
- Time uploaded/joined(?)
- Number of comments
- Tags

This is a fairly large number of things to implement, so we should probably just focus on the lighter side of things...

With just `q`, and with no other parameters added, a full-text search should executed, looking through the names/descriptions/tags of users, lists, and torrents - Where applicable. That should be fairly useful, for now. This entire thing is pretty complicated, and will end up being a pretty big part of the project. We'll have to come back to this later.

**Comment by zegfarce** [comment]
Discussed with pk: We agreed on a system for searching for tags.
`@tag` as a search term gets interpreted as searching within that tag.
e.g. `cat @pets` would search for `cats` within the tag `pets`.
The query so far should be sent all within the `q=` GET parameter.

Other information still needs to be sorted out, like searching by time uploaded/joined, or ratings, for example.
