### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by prettykool** [bit-bandit/parasite#9]
Talk about federation support here.
Check https://www.w3.org/TR/activitypub/#server-to-server-interactions for standard compliance

**Comment by prettykool** [comment]
This wasn't brought up before so; How should allowed/blocked instances be represented in the settings?

**Comment by zegfarce** [comment]
I figure blocking instances should be done like so:
* First, generate a list of instances that we're federating with.
* Next, check for a populated *whitelist*. If there are instances listed in the *whitelist*, only keep those in our list,
* Then, check for a populated *blacklist*. If there are instances listed in the *blacklist*, remove those from our list.
* Finally, federate with those instances that passed both the whitelist and blacklist.

This way, we can have both a whitelist and a blacklist, simultaneously, without things breaking.
We can store the whitelist and blacklist in database tables.

**Comment by prettykool** [comment]
> I figure blocking instances should be done like so:
> 
> * First, generate a list of instances that we're federating with.
> * Next, check for a populated _whitelist_. If there are instances listed in the _whitelist_, only keep those in our list,
> * Then, check for a populated _blacklist_. If there are instances listed in the _blacklist_, remove those from our list.
> * Finally, federate with those instances that passed both the whitelist and blacklist.
> 
> This way, we can have both a whitelist and a blacklist, simultaneously, without things breaking. We can store the whitelist and blacklist in database tables.

This is an interesting way of doing it, but I think there's some slight problems with it, chiefly that it means that we have to *explicitly* put every instance that ever federates with us in the database. That means that, just for a user from one instance to comment on a post from another instance, we'd have to federate the two together. That's dumb. 

What I propose is that:

1. Out of the box, *any* instance can interact with another. It can, however, be disallowed in the site settings.
2. Whitelisted instances mean that items like lists, torrents, and users will be grouped together with the items *on that site*. That doesn't mean that items from *that* site will appear on the other one, however. That requires it to have that instance also included on the sites whitelist.
3. A blacklist means that any incoming requests made by an account on that site, or from the site itself, will be automatically rejected. 

This is fairly simple enough, and doesn't really require a database - Just a simple JSON file can do the job well enough. Tell me if there's any problems with it.

Speaking of which, how will the data be stored? Maybe something like below?:
```json
{
  "allowed": [
    {"name": "https://www.nice.land", "ip":["37.32.142.45"]}
  ],
  "disallowed": [
    {"name": "https://torrents.sickos.social", "ip":["40.32.234.21"]}
  ]
}
```

**Comment by prettykool** [comment]
Update: Zeg has mentioned the idea of making a list of federated instances during the runtime.

**Comment by prettykool** [comment]
Something I brought up outside here again: Although most instances (probably) won't end up growing to the point where it's necessary, a shared outbox would be great for reducing the amounts of HTTP requests a server may have to do while federating.
https://www.w3.org/TR/activitypub/#sharedInbox
https://www.w3.org/TR/activitypub/#shared-inbox-delivery
